Actually submitting a pull request this time... sugo di pomodoro baby
AndrewHaisting/licks pull request #3
Opened 2021-01-28 17:54 UTC by lukekivi

2021-01-28 18:27 UTC, AndrewHaisting requested changes
Welcome to your first code review :)

2021-01-28 18:27 UTC, AndrewHaisting commented on Lucas/Italian/sugo_di_pomodoro-marinara.md
> +a.k.a. Marinara. Make alot and can it. Or not you lazy bastard.
😂 love this

2021-01-28 18:27 UTC, AndrewHaisting commented on Lucas/Italian/sugo_di_pomodoro-marinara.md
> +## Ingrediants:
Typo (maybe its intentional)??

2021-01-28 18:27 UTC, AndrewHaisting commented on Lucas/Italian/sugo_di_pomodoro-marinara.md
> +- **TT** Hot stuff - fresno peppers, chili flake, etc.
👀 I like the TT, gonna start using that

2021-01-28 18:27 UTC, AndrewHaisting commented on Lucas/Italian/sugo_di_pomodoro-marinara.md
> +1. IN a pot brown the garlic in oil. Just until it is golden. Do not let parts of the garlic become **dark** brown or black.
```suggestion
1. In a pot brown the garlic in oil. Just until it is golden. Do not let parts of the garlic become **dark** brown or black.
```

2021-01-28 18:27 UTC, AndrewHaisting commented on Lucas/Italian/sugo_di_pomodoro-marinara.md
> +8. (optional) CAN SOME! Flavors develop over time so even if you do not can, flavor peaks a few days after cooking.
One small tip here, you can use `1.` for all your numbers and the receiving application will figure it out. Just makes it easier if you add or remove steps you don't have to change every damn number.

2021-01-28 18:38 UTC, lukekivi commented on Lucas/Italian/sugo_di_pomodoro-marinara.md
> +8. (optional) CAN SOME! Flavors develop over time so even if you do not can, flavor peaks a few days after cooking.
Interesting. VS code automatically increments for me.

2021-02-03 00:46 UTC, AndrewHaisting approved these changes
Looks great! To keep the commit history clean, I would recommend one of two things:

1) using your terminal squash this branch into one commit, then force push to this branch, then merge
2) on the bottom of the pull request, change "Merge pull request" to be "Squash and merge", and do it through the web 

Both have the same outcome.

2021-02-03 02:34 UTC, merged