Mexican
AndrewHaisting/licks pull request #6
Opened 2021-02-07 20:30 UTC by lukekivi

TORTILLAS MY NINJA

2021-02-07 21:42 UTC, AndrewHaisting requested changes
Everything looks good here, I just have one optional comment about content, and one required change to make this commit history correct.

2021-02-07 21:42 UTC, AndrewHaisting commented on Lucas/Italian/sugo_di_pomodoro-marinara.md
> +8. (optional) CAN SOME! Flavors develop over time so even if you do not can, flavor peaks a few days after cooking.
Whoops! This stuff shouldn't be in this changeset. 

There's lots of ways to solve this, but the root problem is that the commits on `main` don't match the commits you have here. Lots of ways to solve that, though we should probably hop on a call to sort it out, as it its a bit tricky.

2021-02-07 21:42 UTC, AndrewHaisting commented on Lucas/Mexican/flourTortillas.md
> +- **5 T** Animal fat (lard, duck fat, beef fat)
Consider adding a note here about substituting vegetable fat, or blending multiple types of fat.

2021-02-07 21:42 UTC, AndrewHaisting commented on Lucas/Mexican/flourTortillas.md
> +1. Combine flour and fat. Use your fingers in a large bowl, spin in a food processor or use a paddle attachment for a mixer until completely incorporated.
Excellent detail here 👍

2021-02-08 00:47 UTC, lukekivi commented on Lucas/Italian/sugo_di_pomodoro-marinara.md
> +8. (optional) CAN SOME! Flavors develop over time so even if you do not can, flavor peaks a few days after cooking.
I initially pushed the branch without committing changes to the branch. That may be the issue. So then I committed changes and re-pushed and here we are.

2021-02-08 00:50 UTC, lukekivi commented on Lucas/Mexican/flourTortillas.md
> +- **5 T** Animal fat (lard, duck fat, beef fat)
Good point -- the original recipe says he prefers half and half veg - animal actually

2021-02-16 03:29 UTC, lukekivi commented on Lucas/Mexican/flourTortillas.md
> +- **5 T** Animal fat (lard, duck fat, beef fat)
e05dee7ba3a9b8b4fef30d331474bd8ba50992d0 Yep sounds good, changed.

2021-02-16 03:30 UTC, AndrewHaisting commented on Lucas/Mexican/flourTortillas.md
> +- **5 T** Animal fat (lard, duck fat, beef fat)
nice 👍

2021-02-16 03:31 UTC, AndrewHaisting approved these changes
🚀

2021-02-16 03:39 UTC, merged